# Generated by Django 4.2.8 on 2024-01-03 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fooditems", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("meals", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodServing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serving_multiple", models.FloatField()),
                (
                    "food_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fooditems.fooditem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MealOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.IntegerField()),
                (
                    "food_serving",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="foodserving.foodserving",
                    ),
                ),
                (
                    "meal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="meals.meal"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="foodserving",
            name="meals",
            field=models.ManyToManyField(
                through="foodserving.MealOrder", to="meals.meal"
            ),
        ),
        migrations.AddField(
            model_name="foodserving",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
